name: Heroku Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: biggamesurvey

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Select folder application
        run: cd ./server/src/BigGameSurvey.Api/

      - name: Login Heroku
        env:
          HEROKU_API_KEY: $HEROKU_API_KEY
        run: heroku container:login

      - name: Authentication Heroku Registry
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Build and push image
        env:
          HEROKU_API_KEY: $HEROKU_API_KEY
        run: heroku container:push web --app $APP_NAME
        
      - name: Deploy the image
        env:
          HEROKU_API_KEY: $HEROKU_API_KEY
        run: heroku container:release web --app $APP_NAME
      
      - name: Logs deploy
        env:
          HEROKU_API_KEY: $HEROKU_API_KEY
        run: heroku logs --app $APP_NAME --source $APP_NAME --tail
