name: Heroku Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/src/BigGameSurvey.Api/
    env:
      APP_NAME: biggamesurvey

    steps:
      - uses: actions/checkout@v2
        
      - name: test4
        run: pwd

      - name: Authentication Heroku Registry
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Login Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        
        run: heroku container:login

      - name: Build and push image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app $APP_NAME

      - name: Deploy the image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app $APP_NAME
      
      - name: Logs deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku logs --app $APP_NAME --source $APP_NAME --tail
