name: Heroku Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
  APP_NAME: biggamesurvey

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy the Docker image
        run: |
          cd ./server/src/BigGameSurvey.Api/
          docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
          heroku container:push web --app $APP_NAME
          heroku container:release web --app $APP_NAME
      - name: Info publish
        run: heroku logs --source $APP_NAME --tail
