name: Heroku Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
  APP_NAME: biggamesurvey

jobs:
  build:
    # Needs to run in this version
    # Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
    runs-on: ubuntu-16.04
    #runs-on: ubuntu-latest
    
    steps:
      #- uses: actions/checkout@v1
      - uses: actions/checkout@v2

      - name: Build and deploy the Docker image
        run: |
          cd ./server/src/BigGameSurvey.Api/
          docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
          heroku container:push web --app $APP_NAME
          heroku container:release web --app $APP_NAME
